server:
  port: 8081
  servlet:
    session:
      timeout: 30m # 30 分钟
spring:
  application:
    name: my_heima_dianping
  banner:
    location: classpath:myBanner1.txt
  datasource:
    url: jdbc:mysql://121.40.226.231:3306/my_hmdp_database?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zhanhongyu010903
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 121.40.226.231        # Redis 服务器地址
    port: 6379             # Redis 端口号
    password: 123456 # 如果 Redis 没有设置密码，可以省略该项
    timeout: 6000ms        # 连接超时时间
    lettuce:
      pool:
        max-active: 10     # 最大连接数
        max-idle: 8        # 最大空闲连接数
        min-idle: 0        # 最小空闲连接数
logging:
  level:
    root: INFO
    com.hsj.hmdp : debug
  file:
    name: logs\app.logs
    max-size: 10MB
    max-history: 7
