server:
  port: 8081
  servlet:
    session:
      timeout: 30m # 30 分钟
spring:
  application:
    name: my_heima_dianping
  banner:
    location: classpath:myBanner1.txt
  datasource:
    url: jdbc:mysql://121.40.226.231:3306/my_hmdp_database?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zhanhongyu010903
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: root
    com.hsj.hmdp : debug
  file:
    name: logs\app.logs
    max-size: 10MB
    max-history: 7