server:
  port: 8081
  servlet:
    session:
      timeout: 30m # 30 分钟
spring:
  application:
    name: my_heima_dianping
  banner:
    location: classpath:myBanner1.txt
  datasource:
    url: jdbc:mysql://121.40.226.231:3306/my_hmdp_database?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zhanhongyu010903
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js, .gif, .jpg, .png, .css, .ico, /druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: 127.0.0.1
        login-username: admin
        login-password: admin
        # 配置 SQL 监控
        stat-filter:
          enabled: true  # 确保启用了 SQL 监控
          log-slow-sql: true  # 启用慢查询日志
          slow-sql-millis: 1  # 慢查询的阈值，单位毫秒
          merge-sql: true  # 合并同一 SQL 的统计
  redis:
    host: 121.40.226.231        # Redis 服务器地址
    port: 6379             # Redis 端口号
    password: 123456 # 如果 Redis 没有设置密码，可以省略该项
    timeout: 6000ms        # 连接超时时间
    lettuce:
      pool:
        max-active: 10     # 最大连接数
        max-idle: 8        # 最大空闲连接数
        min-idle: 0        # 最小空闲连接数
logging:
  level:
    root: INFO
    com.hsj.hmdp : debug
  file:
    name: logs\app.logs
    max-size: 10MB
    max-history: 7
rocketmq:
  name-server: 121.40.226.231:9876
  producer:
    group: producer-group
  consumer:
    group: consumer-group
    enableDlq: true #开启死信机制
    retryTimesWhenConsumeFailed: 16  # 失败后最大重试 16 次
